# Generated by Django 5.0.3 on 2024-05-14 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coldy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='create_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='delete_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='deletion_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='update_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='updation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='create_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='delete_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='deletion_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='update_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='locationmaster',
            name='updation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='create_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='delete_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deletion_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='update_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
